Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video.urls')),
]

urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Project/video/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.video_new, name='upload'),
    path('charge/', views.charge, name='charge'),
    path('list/', views.video_list, name='list'),
    path('vapi/list', views.video_list_json, name='list_json'),
    path('list/<str:date>', views.video_list, name='list_detail'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout', views.logout_view, name='logout'),
    path('accounts/signup', views.signup, name='signup'),
    path('vapi/<str:year>/<str:month>/<str:day>/<str:filename>', views.video_dump, name='return'),
    path('vapi/<str:year>/<str:month>/<str:day>', views.video_dump, name='return'),
    path('vapi/<str:year>/<str:month>', views.video_dump, name='return'),
    path('vapi/<str:year>', views.video_dump, name='return'),



]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Project/video/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    url = models.URLField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('auth.User', related_name='videos', on_delete=models.CASCADE)
    file = models.FileField(upload_to='videos/%Y/%m/%d', blank=True)
    objects = models.Manager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('video:video_detail', args=[self.id])

    def get_update_url(self):
        return reverse('video:video_update', args=[self.id])

    def get_delete_url(self):
        return reverse('video:video_delete', args=[self.id])

    # delete video file from dir when video is deleted
    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    # get video file name
    def get_file_name(self):
        return self.file.name.split('/')[-1]

Project/video/forms.py
from django import forms
from video.models import Video
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'description', 'file']

    def save(self,user, commit=True):
        vid = Video.objects.create(
            title=self.cleaned_data['title'],
            description=self.cleaned_data['description'],
            file=self.cleaned_data['file'],
            author=user,
        )
        return vid


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise ValidationError('A user with that email already exists.')

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

Project/video/views.py
from django.shortcuts import render, redirect, Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from video.models import Video
from video.forms import VideoForm, UserForm
import json
import hashlib
import cv2
import os


def index(request):
    return render(request, 'video/index.html')


def video_check(file):
    """
    Returns the length of the video in seconds.
    referenced from
    site :- stackoverflow.com
    url:- https://stackoverflow.com/questions/3844430/how-to-get-the-duration-of-a-video-in-python/61572332#61572332

    Charges : 5$ for video below 500MB and 12.5$ above 500MB.
    Additional 12.5$ if the video is under 6 minutes 18 second and
    20$ if above 6 minutes 18 seconds.

    """
    cost = 0
    if file.size < 520000000:  # 500MB
        cost += 5
    else:
        cost += 12.5

    with open("./videos/temp.mp4", "wb") as f:
        f.write(file.read())
    video = cv2.VideoCapture("./videos/temp.mp4")
    frame_count = video.get(cv2.CAP_PROP_FRAME_COUNT)
    fps = video.get(cv2.CAP_PROP_FPS)
    lis = [frame_count / fps, frame_count]
    if lis[0] > 600:
        return {"e": "Video Length Exceeds 10minutes"}
    elif lis[0] < 378:
        cost += 12.5
    elif lis[0] > 378:
        cost += 20
    # remove temp file
    os.remove("./videos/temp.mp4")
    return {"cost": cost}


@login_required
def video_new(request):
    form = VideoForm()
    if request.method == "POST" and request.FILES['file']:
        if request.FILES['file'].size > 1070000000:
            return render(request, 'video/video_new.html', {'form': form, 'error': 'file size is too large.'})
        else:
            res = video_check(request.FILES['file'])
            if 'e' in res.keys():
                form = VideoForm()
                return render(request, 'video/video_new.html', {'form': form, 'error': res['e']})
        if request.FILES['file'].content_type != 'video/mp4':
            return render(request, 'video/video_new.html', {'form': form, 'error': 'file type is not mp4.'})
        request.FILES['file'].name = hashlib.md5(request.FILES['file'].name.encode()
                                                 ).hexdigest() + '.' + request.FILES['file'].name.split('.')[-1]
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            print(request.FILES)
            form.save(request.user)
            return render(request, 'video/video.html', {'form': form, 'success': 'video uploaded successfully.',
                                                        'cost': res['cost']}
                          )

    return render(request, 'video/video.html', {'form': form})


@login_required
def video_list(request):
    if request.method == "GET":
        videos = Video.objects.filter(author=request.user)
    else:
        videos = ""
    return render(request, 'video/video_list.html', {'videos': videos})


@login_required
def video_list_json(request):
    print("Was Here "*100)
    videos = Video.objects.filter(author=request.user)
    if not videos:
        response = {'OOPS': 'NO Videos associated with this user.'}
        return HttpResponse(json.dumps(response), content_type='application/json')
    response = {}
    for n, i in enumerate(videos):
        response[n] = {'year': i.created_at.year,
                       'month': i.created_at.month,
                       'day': i.created_at.day,
                       'filename': i.title,
                       'url': i.file.url}
        print(n, i)
    print(response)
    # returning json response
    return HttpResponse(json.dumps(response), content_type='application/json')


# get object list or 404
def get_object_or_404(model, **kwargs):
    obj = model.objects.filter(**kwargs)
    if not obj:
        raise Http404()
    return obj


# Every USer Get's The list of their videos in JSON
@login_required
def video_dump(request, year=None, month=None, day=None, filename=None):
    user = request.user
    if year and month and day and filename:
        video = get_object_or_404(Video, created_at__year=year, created_at__month=month,
                                  created_at__day=day, filename=filename, author=user)
    elif year and month and day:
        video = get_object_or_404(Video, created_at__year=year, created_at__month=month,
                                  created_at__day=day, author=user)
    elif year and month:
        video = get_object_or_404(Video, created_at__year=year, created_at__month=month, author=user)
    elif year:
        video = get_object_or_404(Video, created_at__year=year, author=user)
    else:
        video = get_object_or_404(Video, filename=filename, author=user)
    response = {}
    for n, i in enumerate(video):
        response[n] = {'year': i.created_at.year,
                       'month': i.created_at.month,
                       'day': i.created_at.day,
                       'filename': i.title,
                       'url': i.file.url}
        print(n, i)
    print(response)
    # returning json response
    return HttpResponse(json.dumps(response), content_type='application/json')


@login_required
def charge(request):
    return render(request, 'video/charge.html')


# signup
def signup(request):
    error=''
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return redirect('list')
        else:
            error = form.errors

    else:
        form = UserForm()
    return render(request, 'video/signup.html', {'form': form, 'error': error})


# login and logout using django.contrib.auth
def login_view(request):
    print(request.user.is_authenticated * 10)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('list')
        else:
            return render(request, 'video/login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'video/login.html')


def logout_view(request):
    logout(request)
    return redirect('index')

Project/templates/video/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HOME</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Raleway:400,700');

* {
	box-sizing: border-box;
	margin: 0;
	padding: 0;
	font-family: Raleway, sans-serif;
}

body {
	background: linear-gradient(90deg, #C7C5F4, #776BCC);
}

.container {
	display: flex;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
}

.screen {
	background: linear-gradient(90deg, #5D54A4, #7C78B8);
	position: relative;
	height: 600px;
	width: 360px;
	box-shadow: 0px 0px 24px #5C5696;
}

.screen__content {
	z-index: 1;
	position: relative;
	height: 100%;
}

.screen__background {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 0;
	-webkit-clip-path: inset(0 0 0 0);
	clip-path: inset(0 0 0 0);
}

.screen__background__shape {
	transform: rotate(45deg);
	position: absolute;
}

.screen__background__shape1 {
	height: 520px;
	width: 520px;
	background: #FFF;
	top: -50px;
	right: 120px;
	border-radius: 0 72px 0 0;
}

.screen__background__shape2 {
	height: 220px;
	width: 220px;
	background: #6C63AC;
	top: -172px;
	right: 0;
	border-radius: 32px;
}

.screen__background__shape3 {
	height: 540px;
	width: 190px;
	background: linear-gradient(270deg, #5D54A4, #6A679E);
	top: -24px;
	right: 0;
	border-radius: 32px;
}

.screen__background__shape4 {
	height: 400px;
	width: 200px;
	background: #7E7BB9;
	top: 420px;
	right: 50px;
	border-radius: 60px;
}

.login {
	width: 320px;
	padding: 20px;
	//padding-top: 156px;
}

.login__field {
	padding: 15px 0px;
	position: relative;
}

.login__icon {
	position: absolute;
	top: 30px;
	color: #7875B5;
}

.login__input {
	border: none;
	border-bottom: 2px solid #D1D1D4;
	background: none;
	padding: 10px;
	padding-left: 24px;
	font-weight: 700;
	width: 75%;
	transition: .2s;
}

.login__input:active,
.login__input:focus,
.login__input:hover {
	outline: none;
	border-bottom-color: #6A679E;
}

.login__submit {
	background: #fff;
	font-size: 14px;
	margin-top: 30px;
	padding: 16px 20px;
	border-radius: 26px;
	border: 1px solid #D4D3E8;
	text-transform: uppercase;
	font-weight: 700;
	display: flex;
	align-items: center;
	width: 100%;
	color: #4C489D;
	box-shadow: 0px 2px 2px #5C5696;
	cursor: pointer;
	transition: .2s;
}

.login__submit:active,
.login__submit:focus,
.login__submit:hover {
	border-color: #6A679E;
	outline: none;
}

.button__icon {
	font-size: 24px;
	margin-left: auto;
	color: #7875B5;
}

.social-login {
	position: absolute;
	height: 140px;
	width: 160px;
	text-align: center;
	bottom: 0px;
	right: 50px;
	color: #fff;
}

.social-icons {
	display: flex;
	align-items: center;
	justify-content: center;
}

.social-login__icon {
	padding: 20px 10px;
	color: #fff;
	text-decoration: none;
	text-shadow: 0px 0px 8px #7875B5;
}

.social-login__icon:hover {
	transform: scale(1.5);
}
    </style>
</head>
<body>
<div>

</div>
<div class="container">
	<div class="screen">
		<div class="screen__content">
            <div style="padding-top:10%;padding-left:5%;color:#8855dd;">
			<h1>VideoStore</h1>
		</div>
            <div style="padding-top:10%;padding-left:10%;color:#5500ffaa">
			<h1>HOME</h1>
		</div>
        <div class="social-login">
				<div class="social-icons">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout'%}" class="social-login__icon">Logout</a>
                    <a href="{% url 'upload'%}" class="social-login__icon">Upload</a>
                    <a href="{% url 'list'%}" class="social-login__icon">List</a>
					<a href="{% url 'index'%}" class="social-login__icon">Home</a>
                    {% else %}
					<a href="{% url 'signup'%}" class="social-login__icon">SignUp</a>
                    <a href="{% url 'login'%}" class="social-login__icon">Login</a>
					<a href="{% url 'index'%}" class="social-login__icon">Home</a>
                    {% endif %}
				</div>
			</div>
            </div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>

</body>
</html>

Project/templates/video/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Raleway:400,700');

* {
	box-sizing: border-box;
	margin: 0;
	padding: 0;
	font-family: Raleway, sans-serif;
}

body {
	background: linear-gradient(90deg, #C7C5F4, #776BCC);
}

.container {
	display: flex;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
}

.screen {
	background: linear-gradient(90deg, #5D54A4, #7C78B8);
	position: relative;
	height: 600px;
	width: 360px;
	box-shadow: 0px 0px 24px #5C5696;
}

.screen__content {
	z-index: 1;
	position: relative;
	height: 100%;
}

.screen__background {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 0;
	-webkit-clip-path: inset(0 0 0 0);
	clip-path: inset(0 0 0 0);
}

.screen__background__shape {
	transform: rotate(45deg);
	position: absolute;
}

.screen__background__shape1 {
	height: 520px;
	width: 520px;
	background: #FFF;
	top: -50px;
	right: 120px;
	border-radius: 0 72px 0 0;
}

.screen__background__shape2 {
	height: 220px;
	width: 220px;
	background: #6C63AC;
	top: -172px;
	right: 0;
	border-radius: 32px;
}

.screen__background__shape3 {
	height: 540px;
	width: 190px;
	background: linear-gradient(270deg, #5D54A4, #6A679E);
	top: -24px;
	right: 0;
	border-radius: 32px;
}

.screen__background__shape4 {
	height: 400px;
	width: 200px;
	background: #7E7BB9;
	top: 420px;
	right: 50px;
	border-radius: 60px;
}

.login {
	width: 320px;
	padding: 30px;
	padding-top: 156px;
}

.login__field {
	padding: 20px 0px;
	position: relative;
}

.login__icon {
	position: absolute;
	top: 30px;
	color: #7875B5;
}

.login__input {
	border: none;
	border-bottom: 2px solid #D1D1D4;
	background: none;
	padding: 10px;
	padding-left: 24px;
	font-weight: 700;
	width: 75%;
	transition: .2s;
}

.login__input:active,
.login__input:focus,
.login__input:hover {
	outline: none;
	border-bottom-color: #6A679E;
}

.login__submit {
	background: #fff;
	font-size: 14px;
	margin-top: 30px;
	padding: 16px 20px;
	border-radius: 26px;
	border: 1px solid #D4D3E8;
	text-transform: uppercase;
	font-weight: 700;
	display: flex;
	align-items: center;
	width: 100%;
	color: #4C489D;
	box-shadow: 0px 2px 2px #5C5696;
	cursor: pointer;
	transition: .2s;
}

.login__submit:active,
.login__submit:focus,
.login__submit:hover {
	border-color: #6A679E;
	outline: none;
}

.button__icon {
	font-size: 24px;
	margin-left: auto;
	color: #7875B5;
}

.social-login {
	position: absolute;
	height: 140px;
	width: 160px;
	text-align: center;
	bottom: 0px;
	right: 0px;
	color: #fff;
}

.social-icons {
	display: flex;
	align-items: center;
	justify-content: center;
}

.social-login__icon {
	padding: 20px 10px;
	color: #fff;
	text-decoration: none;
	text-shadow: 0px 0px 8px #7875B5;
}

.social-login__icon:hover {
	transform: scale(1.5);
}
    </style>
</head>
<body>

<div class="container">
	<div class="screen">
		<div class="screen__content">
            <div style="padding-top:10%;padding-left:10%;color:#5500fa">
			<h2>LOGIN</h2>
		</div>
			<form class="login" action="" method="post">
                {% if error %}
                <span style="color:#f50000">
				{{error}}
				</span>
                {% endif %}
                {%csrf_token%}
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="text" class="login__input" placeholder="User name"
                           name="username" id="username" required>
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
					<input type="password" class="login__input" placeholder="Password"
                           name="password" id="password" required>
				</div>
				<button class="button login__submit">
					<span class="button__text">Log In Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>
			</form>

        <div class="social-login">
				<h3>Go To</h3>
				<div class="social-icons">
					<a href="{% url 'signup'%}" class="social-login__icon">SignUp</a>
					<a href="{% url 'index'%}" class="social-login__icon">Home</a>
				</div>
			</div>
            </div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>

</body>
</html>

Project/templates/video/video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Uploader</title>
       <style>
        @import url('https://fonts.googleapis.com/css?family=Raleway:400,700');

* {
	box-sizing: border-box;
	margin: 0;
	padding: 0;
	font-family: Raleway, sans-serif;
}

body {
	background: linear-gradient(90deg, #C7C5F4, #776BCC);
}

.container {
	display: flex;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
}

.screen {
	background: linear-gradient(90deg, #5D54A4, #7C78B8);
	position: relative;
	height: 600px;
	width: 360px;
	box-shadow: 0px 0px 24px #5C5696;
}

.screen__content {
	z-index: 1;
	position: relative;
	height: 100%;
}

.screen__background {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 0;
	-webkit-clip-path: inset(0 0 0 0);
	clip-path: inset(0 0 0 0);
}

.screen__background__shape {
	transform: rotate(45deg);
	position: absolute;
}

.screen__background__shape1 {
	height: 520px;
	width: 520px;
	background: #FFF;
	top: -50px;
	right: 120px;
	border-radius: 0 72px 0 0;
}

.screen__background__shape2 {
	height: 220px;
	width: 220px;
	background: #6C63AC;
	top: -172px;
	right: 0;
	border-radius: 32px;
}

.screen__background__shape3 {
	height: 540px;
	width: 190px;
	background: linear-gradient(270deg, #5D54A4, #6A679E);
	top: -24px;
	right: 0;
	border-radius: 32px;
}

.screen__background__shape4 {
	height: 400px;
	width: 200px;
	background: #7E7BB9;
	top: 420px;
	right: 50px;
	border-radius: 60px;
}

.login {
	width: 320px;
	padding: 20px;
	//padding-top: 156px;
}

.login__field {
	padding: 15px 0px;
	position: relative;
}

.login__icon {
	position: absolute;
	top: 30px;
	color: #7875B5;
}

.login__input {
	border: none;
	border-bottom: 2px solid #D1D1D4;
	background: none;
	padding: 10px;
	padding-left: 24px;
	font-weight: 700;
	width: 75%;
	transition: .2s;
}

.login__input:active,
.login__input:focus,
.login__input:hover {
	outline: none;
	border-bottom-color: #6A679E;
}

.login__submit {
	background: #fff;
	font-size: 14px;
	margin-top: 30px;
	padding: 16px 20px;
	border-radius: 26px;
	border: 1px solid #D4D3E8;
	text-transform: uppercase;
	font-weight: 700;
	display: flex;
	align-items: center;
	width: 100%;
	color: #4C489D;
	box-shadow: 0px 2px 2px #5C5696;
	cursor: pointer;
	transition: .2s;
}

.login__submit:active,
.login__submit:focus,
.login__submit:hover {
	border-color: #6A679E;
	outline: none;
}

.button__icon {
	font-size: 24px;
	margin-left: auto;
	color: #7875B5;
}

.social-login {
	position: absolute;
	height: 140px;
	width: 160px;
	text-align: center;
	bottom: 0px;
	right: 50px;
	color: #fff;
}

.social-icons {
	display: flex;
	align-items: center;
	justify-content: center;
}

.social-login__icon {
	padding: 20px 10px;
	color: #fff;
	text-decoration: none;
	text-shadow: 0px 0px 8px #7875B5;
}

.social-login__icon:hover {
	transform: scale(1.5);
}
    </style>
	<style>
	input[type="file" i] {
	appearance: none;
    background-color: initial;
    cursor: grabbing;
    opacity: 50;
    align-items: baseline;
    color: inherit;
    text-overflow: ellipsis;
    white-space: pre;
    text-align: start !important;
    padding: initial;
    border: initial;
    overflow: hidden !important;
    }
	</style>
</head>
<body>

<div class="container">
	<div class="screen">
		<div class="screen__content">
            <div class="screen__content">
            <div style="padding-top:10%;padding-left:5%;color:#8855dd;">
			<h1>VideoStore</h1>
		</div>
				{% if cost %}
				<div style="padding-top:10%;padding-left:10%;color:#5500ffaa">
			<p>It costed you <b style="color:#ff55ffff"> {{ cost }}$ </b>for last upload.</p>
		</div>
{% endif %}
<div class="error">
            {% if error %}
                <span style="color:#f50000">
				{{error}}
				</span>
                {% endif %}
	</div>

			<form class="login" action="" method="post" enctype="multipart/form-data">

                {%csrf_token%}

				<div class="login__field">
					<input type="text" name="title" maxlength="200" required id="id_title" class="login__input">
				</div>
				<div class="login__field">
					<textarea name="description" cols="40" rows="10" id="id_description"
                              style="height: 67px; width: 240px;" class="login__input"></textarea>
				</div>
                	<div class="login__field">
                 		<input type="file" name="file" id="id_file" class="login__input">
                    </div>
				<button class="button login__submit">
					<span class="button__text">Upload</span>
				</button>
			</form>

         <div class="social-login">
				<div class="social-icons">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout'%}" class="social-login__icon">Logout</a>
                    <a href="{% url 'list'%}" class="social-login__icon">list</a>
					<a href="{% url 'index'%}" class="social-login__icon">Home</a>
                    {% else %}
					<a href="{% url 'signup'%}" class="social-login__icon">SignUp</a>
                    <a href="{% url 'login'%}" class="social-login__icon">Login</a>
					<a href="{% url 'index'%}" class="social-login__icon">Home</a>
                    {% endif %}
				</div>
			</div>
            </div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>

</div>
</body>
<script>
	//fade out error div
	var error = document.getElementsByClassName("error")[0];
	error.style.display = "none";
	setTimeout(function() {
		error.style.display = "none";
	}, 50);
</script>
</html>